import streamlit as st

def introduction():
    st.title('Product Segmentation for Retail 🛍️')
    st.markdown('''
        _For more information about the theory behind: **[Article - Product Segmentation for Retail](https://towardsdatascience.com/product-segmentation-for-retail-with-python-c85cc0930f9a)**_
    ''')
    with st.beta_expander('''How can this app help you?'''):
        st.write('''This Streamlit Web Application has been designed for **Supply Chain Engineers** to support them in their **Inventory Management**.
        It will help you to automate **product segmentation using statistics**.''')
        st.markdown(
    """
    1. Upload a dataset or use the example 💾 
    2. Pick a model and set its hyper-parameters ⚙️ 
    3. Train it and check its performance metrics and decision boundary on train and test data 📉 
    4. Diagnose possible overitting and experiment with other settings 🩺 
    """)

def dataset_ui(df_abc, df, dataset_type):
    # Show Features
    st.subheader("🔧 Please select columns for the following features")
    columns = df.columns
    # st.write(list(columns))
    col1, col2 = st.beta_columns(2)
    with col1:
        date_col = st.selectbox("Select date column",index= len(df.columns) - 2,options=columns,key="date")
    with col2:
        metric_col = st.selectbox("Select values column",index=len(df.columns)-1,options=columns,key="values")
    output = 0 

    st.subheader('🛎️ Please choose the following features in your dataset')
    with st.beta_expander("Features to use for the analysis"):
        st.markdown('''
        Select the columns that you want to include in the analysis of your sales records._
    ''')
        dict_var = {}
        for column in df.columns:
            dict_var[column] = st.checkbox("{} (IN/OUT)".format(column), value = 1)

    if dataset_type == 'UPLOADED':
        with st.beta_expander("Features for the SKU information (ID, STORE, FAMILY)"):
            st.markdown('''
        Select the columns used for product master data (SKU ID, Family, Category, Store Location)_
    ''')
            dict_sku = {}
            for column in df.columns:
                if column in ['SKU', 'ITEM', 'FAMILY', 'CATEGORY', 'STORE']:
                    val = 1
                else:
                    val = 0
                dict_sku[column] = st.checkbox("{} (YES/NO)".format(column) , value = val)
    else:
        with st.beta_expander("Features for the SKU information (ID, STORE, FAMILY)"):
            st.markdown('''
        _Select the columns used for product master data (SKU ID, Family, Category, Store Location)_
    ''')
            dict_sku = {}
            for column in df.columns:
                if column in ['SKU', 'ITEM', 'FAMILY', 'CATEGORY', 'STORE']:
                    val = 1
                else:
                    val = 0
                dict_sku[column] = st.checkbox("{} (YES/NO)".format(column) , value = val)

    with st.beta_expander("Features for the SKU FAMILY"):
        st.markdown('''
        _Select the column you want to use to group your SKUs (Category, Sub-Category, Department)_
    ''')
        family_col = st.selectbox("Select a column for the product family", index= 3,options=columns,key="date")

    filtered = filter(lambda col: dict_var[col]==1, df.columns)
    list_var =list(filtered)

    filtered = filter(lambda col: dict_sku[col]==1, df.columns)
    list_sku =list(filtered)


    return date_col, metric_col, list_var, list_sku, family_col

def pareto_ui(df_abc, nsku_qty80, qty_nsku20):
    col1,col2 = st.beta_columns(2)
    with col1:
        st.write('80% of your volume is generated by **{}% for your SKU portofolio**'.format(nsku_qty80))
    with col2:    
        st.write('20% of your SKU portofolio represent **{}% for your volume**'.format(qty_nsku20))

def abc_ui(df):
    st.header("**ABC Analysis using Coefficient of Variation 🛠️**")
    col1, col2= st.beta_columns(2)
    with col1:
        interval = st.slider(
            'set the maximum value for y-axis CV',
            0, 
            int(df['CV'].max())
            , value = 4)
    with col2:
        n_classes1 = st.number_input("centers", 2, 5, 2, 1)
    st.write(interval)

    return interval


def normality_ui():
    st.header("**Normality Test 🛠️**")
    st.markdown(
        '''_Can we reject the null hypothesis that the sales distribution of the item follows a normal distribution?_
''')
    st.markdown(
        '''
This model is using the Shapiro-Wilk test for normality implemented using Scipy library of python 
_(**[Documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html)**)_.
''')

def distribution_ui():
    st.header("**Example of distributions with a low CV 🛠️**")
    st.markdown(
    '''
    _A rule of thumb to estimate the normality of a distribution is to 
    assume that below 0.5 you can assumte that the distribution is normal._
    ''')
    